version: '3.8'
services:
  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/opt/prometheus/prometheus.yml

  nodeexporter:
    build: ./node-exporter
    ports:
      - "9100:9100"

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"

  microservice:
    build: ./microservice
    ports:
      - "5000:5000"

