- hosts: monitoring
  tasks:
    - name: Run Prometheus container
      docker_container:
        name: prometheus
        image: custom_prometheus
        ports:
          - "9090:9090"
        restart_policy: always

    - name: Run Node Exporter
      docker_container:
        name: nodeexporter
        image: custom_nodeexporter
        ports:
          - "9100:9100"
        restart_policy: always

    - name: Run Grafana
      docker_container:
        name: grafana
        image: custom_grafana
        ports:
          - "3000:3000"
        restart_policy: always

